### ISSUE TITLE
Type errors when using td.Compiler.init_loom() or eval()

### ISSUE THREAD

**Issue by Yan-Huang-Cam** [tensorflow/fold#11]
Hi,

I kept getting the following message when using td.Compiler.init_loom() or eval():

"TypeError: Expected int32, got list containing Tensors of type '_Message' instead"

The error message came up even when I followed the simple examples in the Quick Start Notebook, like:
"scalar_block = td.Scalar()
scalar_block.eval(42)"

My Tensorflow version is 0.12.1. I was wondering if you had any idea about how to fix this?

Thanks a lot for your attention and time!

**Comment by ronghanghu** [comment]
From the document, it seems that you need at least TensorFlow 1.0 to run TensorFlow Fold

**Comment by Yan-Huang-Cam** [comment]
Thank you very much! Sorry for neglecting this information in the documentation earlier. The problem is solved after upgrading TF
