### ISSUE TITLE
Inverse of td.Zip()?

### ISSUE THREAD

**Issue by tttr222** [tensorflow/fold#20]
td.Zip() takes a tuple of sequences and converts it to a sequence of tuples.

Is there a straightforward way to do the inverse of td.Zip()? 

i.e. Take a sequence of tuples and converts it to a tuple of sequences.

**Comment by fkm3** [comment]
Didn't test, but I assume this works:
```python
td.AllOf(td.Map(td.GetItem(0)), td.Map(td.GetItem(1)))
```

**Comment by tttr222** [comment]
Works great, thanks!
