### ISSUE TITLE
What is the most appropriate way to add additional features to each node in a tree-like input?

### ISSUE THREAD

**Issue by arwhirang** [tensorflow/fold#29]
Suppose I have a certain input like below
`Fold is a nice library.`
,which can be converted like below.
(4 (3 Fold) (3 (3 (3 is) (3 (3 a) (3 (5 nice) (3 library)))) (3 .)))

The binary tree format string can be an input for the [sentiment model](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/sentiment.ipynb). I tried to find a way for assigning additional features for each node in a tree. And by changing the label of each node, (for example, (3 Fold) => (3/NP Fold)) I could transfer additional features to the model. But it seems a bit clumsy way for me. 

Is there any other way to add additional features to each node?

**Comment by moshelooks** [comment]
well, sentiment model example is written to demonstrate how to combine
preprocessing (in this case parsing s-expressions from strings) with
modeling. Probably the simplest way to do what you want is to break out the
preprocessing as a separate step (either with an InputTransform or just
directly in python before Fold ever sees the data), add the features that
you'd like, then pass the s-expression directly to a version of the
sentiment model that doesn't do preprocessing but expects an s-expression
as input. This should be quite simple, just drop
the td.InputTransform(tokenize) block from the model, and call tokenize
yourself along with adding your extra features.

**Comment by arwhirang** [comment]
Well... I have been trying it. But somehow, I feel like the model's performance becomes worse when I just add features to the label part (even if I do not use the additional features)

I will keep trying it.
