### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by yohokuno** [tensorflow/fold#3]
Can I use it on Mac OS X? I'm on El capitan 10.11.6.

**Comment by delesley** [comment]
Probably, although we haven't verified it.  We're a very small team, so there's no way we can test and distribute for every platform.  However, feel free to compile from source, and let us know if you run into any problems.

**Comment by yohokuno** [comment]
@delesley Thank you for replying me.

I have no experience in bazel but I got the following error when running bazel command on top directory.

Unexpected error reading .blazerc file '/Users/yookuno/src/fold/tensorflow/tools/bazel.rc'

I gave up Mac and switched to Ubuntu eventually.

**Comment by illegalplumbing** [comment]
Anyone got it working ?
I am getting "pointer being freed was not allocated" exception when loading tensorflow_fold.
Tensorflow itself works fine (no GPU setup)

here is what lldb prints out:
  ...
 frame #15: 0x0000000105f6f3b1 _pywrap_tensorflow.so`tensorflow::internal::LoadLibrary(char const*, void**) + 49
    frame #16: 0x0000000105f6e944 _pywrap_tensorflow.so`tensorflow::(anonymous namespace)::PosixEnv::LoadLibrary(char const*, void**) + 20
    frame #17: 0x0000000105e91563 _pywrap_tensorflow.so`tensorflow::LoadLibrary(char const*, void**, void const**, unsigned long*) + 1075
    frame #18: 0x000000010443ed74 _pywrap_tensorflow.so`TF_LoadLibrary + 52
    frame #19: 0x0000000104360222 _pywrap_tensorflow.so`_wrap_TF_LoadLibrary(_object*,
...

Thank you !
IP

**Comment by pkuso** [comment]
I met the same issue @illegalplumbing  ~ any solutions so far?
