### ISSUE TITLE
TensorFlow for Python 3.3

### ISSUE THREAD

**Issue by ch3njust1n** [tensorflow/fold#33]
Trying to get the follow to work:
`pip3 install https://storage.googleapis.com/tensorflow_fold/tensorflow_fold-0.0.1-py3-none-linux_x86_64.whl`, but seems like there's not support for TensorFlow in Python 3.3. Also there's a typo in the setup. The Python 3.3 instructions says `pip, but it should be `pip3`. Anyways, can't get this working for Python 3.3 since there doesn't seem to be support for TF in Python3.3.

**Comment by moshelooks** [comment]
Please follow the instructions carefully and create a virtual environment
using "virtualenv -p python3 foo" for python3 like we say. If you do this
then once you activate the virtual environment pip will be an alias for
pip3.  You're right, it does look like TF is dropping support for 3.3 going
forward unfortunately.

**Comment by ch3njust1n** [comment]
Hmm ok thanks
