### ISSUE TITLE
How to concatenate sequences?

### ISSUE THREAD

**Issue by gao19920804** [tensorflow/fold#47]
td.Concat only concatenates a tuple of tensors. But the output of td.Map is sequence. How can I concatenate it?

`A_block = (td.Map(td.Scalar('int32') >> td.Function(td.Embedding(10, 4))) >> td.Reduce(td.Concat() >> td.Function(td.FC(4))))`
`result = td.Map(A_block) >> td.Concat()`

TypeError: bad input type SequenceType for <td.Concat concat_dim=0 flatten=False>, expected TupleType

I tried to use td.Reduce(td.Concat()). But it will raise error, if I do not add td.FC(4).
`result = td.Map(A_block) >> td.Reduce(td.Concat() >> td.FC(4))`

How to concatenate a sequence and don't reduce to shape(4,) ?  Thank you very much.

**Comment by delesley** [comment]
Please see:  https://github.com/tensorflow/fold/issues/31
