### ISSUE TITLE
can't feed tuple to map

### ISSUE THREAD

**Issue by blythed** [tensorflow/fold#77]
I am attempting the blocks tutorial. Here's my code:

```python
import tensorflow_fold as td
import tensorflow as tf

sess = tf.Session()

char_cell = td.ScopedLayer(tf.contrib.rnn.BasicLSTMCell(num_units=16), 'char_cell')
word_cell = td.ScopedLayer(tf.contrib.rnn.BasicLSTMCell(num_units=32), 'word_cell')

char_lstm = (td.InputTransform(lambda s: [ord(c) for c in s]) >>
             td.Map(td.Scalar('int32') >>
             td.Function(td.Embedding(128, 8))) >>
             td.RNN(char_cell))

word_lstm = td.Map(char_lstm >> td.GetItem(1)) >> td.RNN(word_cell)

print char_lstm.eval("man", session=sess) # this works fine
print word_lstm.eval(("a", "man"), session=sess) # AttributeError: 'tuple' object has no attribute 'get_shape
```
The error is printed in the comment
However the td.Map documentation says that it takes tuples as inputs.
Any help would be greatly appreciated.

**Comment by tadpole** [comment]
The output of char_lstm is (output\_sequence, final\_state), see [this](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/py/td.md#tdrnncell-initial_statenone-initial_state_from_inputfalse-namenone).
Above code use `td.Map(char_lstm >> td.GetItem(1))` to get final\_state which is a tuple (new\_h, new\_c) actually. 
`td.RNN(word_cell)` need a sequence of new\_h, so when it tries to call get_shape on get\_h, it calls get_shape on tuple  (new\_h, new\_c). 

I think the `word_lstm` should be like this:
```
 word_lstm = td.Map(char_lstm >> td.GetItem(1) >> td.GetItem(0)) >> td.RNN(word_cell)
```

**Comment by pklfz** [comment]
see issue #54 and pr #63
