### ISSUE TITLE
"undefined symbol" caused by building fold from source

### ISSUE THREAD

**Issue by Qilewuqiong** [tensorflow/fold#88]
Hello,
I build fold and tensorflow from source by instructions in "https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/sources.md".  However, when I impement "import tensorflow_fold as td" I get the error:

tensorflow.python.framework.errors_impl.NotFoundError: /home/xxx/.local/lib/python3.5/site-packages/tensorflow_fold/loom/_deserializing_weaver_op.so: undefined symbol: _ZN10tensorflow7strings6

 Also I have tried install tensorflow-1.0 and 1.4 directly from network by pip , but the error still exist.  

Implementing "ldd _deserializing_weaver_op.so" output the following information: 
        linux-vdso.so.1 =>  (0x00007fff972d2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f76c2ab6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76c27ad000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f76c242a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76c2214000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76c1e4a000)
        /lib64/ld-linux-x86-64.so.2 (0x0000562a389c0000)

**Comment by ShangyanLi** [comment]
@Qilewuqiong any hint as to how to solve this issue? I'm installing tensorflow-fold on Ubuntu 16.04 with Python 3.5 and ran into the same error

**Comment by Qilewuqiong** [comment]
The problem may be caused by the incompatibility between the version of tensorflow you installed and that of tensorflow fold. Try to recompile tensorflow fold from source. I currently use tensorflow-1.0 and no problem occurs.

**Comment by ShangyanLi** [comment]
Thanks! Solved the problem by uninstalling the latest version and installing 1.0
